spring:
  profiles:
    active: dev
  # druid 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/seata_account?allowMultiQueries=true&autoReconnect=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useUnicode=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat,wall,slf4j
    maxActive: 20
    initialSize: 5
    maxWait: 60000
    minIdle: 5
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

mybatis-plus:
  typeAliasesPackage: 'com.javasea.account.entity'
  #  config-location: classpath:mybatis/mybatis.cfg.xml
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  global-config:
    db-config:
      field-strategy: not-empty
      id-type: auto
      db-type: mysql
  configuration:
    # 驼峰下划线映射
    map-underscore-to-camel-case: true
    cache-enabled: false
    auto-mapping-unknown-column-behavior: none
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 106.12.11.240:8848
      namespace:
  #      userName: "nacos"
  #      password: "nacos"
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: 106.12.11.240:8848
      group: SEATA_GROUP
#      userName: "nacos"
#      password: "nacos"
